FROM debian:11-slim

WORKDIR /app
ENV TEST tba

CMD echo "TEST: ${TEST}"

#FROM swaggerapi/petstore3:1.0.11
#
#WORKDIR /swagger-petstore
#EXPOSE 8080
#CMD ["java", "-jar", "-DswaggerUrl=openapi.yaml", "/swagger-petstore/jetty-runner.jar", "--log", "/var/log/yyyy_mm_dd-requests.log", "/swagger-petstore/server.war"]
